name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-vote-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build Docker image for vote-api
      run: docker build -t vote-api ./vote-api

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag vote-api $DOCKER_USERNAME/vote-api:latest
        docker push $DOCKER_USERNAME/vote-api:latest

    - name: Deploy vote-api to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '' \
          https://api.render.com/deploy/srv-ctdjf3ij1k6c73dqppb0

  build-and-deploy-web-client:
    runs-on: ubuntu-latest
    needs: build-and-deploy-vote-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Build Docker image for web-client
      run: docker build -t web-client ./web-client

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag web-client $DOCKER_USERNAME/web-client:latest
        docker push $DOCKER_USERNAME/web-client:latest

    - name: Deploy web-client to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '' \
          https://api.render.com/deploy/srv-cteeidrtq21c73bilsfg

  build-and-deploy-docs:
    runs-on: ubuntu-latest
    needs: build-and-deploy-web-client

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'
    - name: Install dependencies for docs
      run: npm install --legacy-peer-deps
      working-directory: docs

    - name: Build the docs site
      run: npm run build
      working-directory: docs

    - name: Build Docker image for docs
      run: docker build -t docs ./docs

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag docs $DOCKER_USERNAME/docs:latest
        docker push $DOCKER_USERNAME/docs:latest
  
    - name: Deploy docs to Netlify
      uses: nwtgck/actions-netlify@v1.2.3
      with:
        publish-dir: docs/build
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}